function tau_frcn = F_vctr_fcn(in1,in2)
%F_VCTR_FCN
%    TAU_FRCN = F_VCTR_FCN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    25-Mar-2020 14:56:46

pi_frcn_11 = in2(1,:);
pi_frcn_21 = in2(2,:);
pi_frcn_31 = in2(3,:);
pi_frcn_41 = in2(4,:);
pi_frcn_51 = in2(5,:);
pi_frcn_61 = in2(6,:);
pi_frcn_71 = in2(7,:);
pi_frcn_81 = in2(8,:);
pi_frcn_91 = in2(9,:);
pi_frcn_101 = in2(10,:);
pi_frcn_111 = in2(11,:);
pi_frcn_121 = in2(12,:);
pi_frcn_131 = in2(13,:);
pi_frcn_141 = in2(14,:);
pi_frcn_151 = in2(15,:);
pi_frcn_161 = in2(16,:);
pi_frcn_171 = in2(17,:);
pi_frcn_181 = in2(18,:);
qd1 = in1(1,:);
qd2 = in1(2,:);
qd3 = in1(3,:);
qd4 = in1(4,:);
qd5 = in1(5,:);
qd6 = in1(6,:);
tau_frcn = [pi_frcn_31+pi_frcn_11.*qd1+pi_frcn_21.*sign(qd1);pi_frcn_61+pi_frcn_41.*qd2+pi_frcn_51.*sign(qd2);pi_frcn_91+pi_frcn_71.*qd3+pi_frcn_81.*sign(qd3);pi_frcn_121+pi_frcn_101.*qd4+pi_frcn_111.*sign(qd4);pi_frcn_151+pi_frcn_131.*qd5+pi_frcn_141.*sign(qd5);pi_frcn_181+pi_frcn_161.*qd6+pi_frcn_171.*sign(qd6)];
