function pos = position_fk_UR10E(in1)
%POSITION_FK_UR10E
%    POS = POSITION_FK_UR10E(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    31-Jan-2020 07:44:23

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
q4 = in1(4,:);
t2 = sin(1.57079632679);
t3 = cos(q1);
t4 = cos(q2);
t5 = cos(q3);
t6 = sin(q2);
t7 = sin(q3);
t8 = sin(q1);
t9 = cos(q4);
t10 = sin(q4);
pos = [t8.*(-8.7e1./5.0e2)-t2.*t9.*(t2.*t3.*t4.*t7+t2.*t3.*t5.*t6).*(3.0./2.5e1)-t2.*t10.*(t2.*t3.*t4.*t5-t2.*t3.*t6.*t7).*(3.0./2.5e1)+t2.*t3.*t4.*(6.13e2./1.0e3)+t2.*t3.*t4.*t5.*(5.71e2./1.0e3)-t2.*t3.*t6.*t7.*(5.71e2./1.0e3);t3.*(8.7e1./5.0e2)-t2.*t9.*(t2.*t4.*t7.*t8+t2.*t5.*t6.*t8).*(3.0./2.5e1)-t2.*t10.*(t2.*t4.*t5.*t8-t2.*t6.*t7.*t8).*(3.0./2.5e1)+t2.*t4.*t8.*(6.13e2./1.0e3)+t2.*t4.*t5.*t8.*(5.71e2./1.0e3)-t2.*t6.*t7.*t8.*(5.71e2./1.0e3);t2.*t6.*(-6.13e2./1.0e3)-t2.*t9.*(t2.*t4.*t5-t2.*t6.*t7).*(3.0./2.5e1)+t2.*t10.*(t2.*t4.*t7+t2.*t5.*t6).*(3.0./2.5e1)-t2.*t4.*t7.*(5.71e2./1.0e3)-t2.*t5.*t6.*(5.71e2./1.0e3)+1.81e2./1.0e3];
