/*
 * File: G_vctr_fcn.c
 *
 * MATLAB Coder version            : 4.1
 * C/C++ source code generated on  : 25-Mar-2020 16:43:47
 */

/* Include Files */
#include <math.h>
#include "G_vctr_fcn.h"

/* Function Definitions */

/*
 * G_VCTR_FCN
 *     G_VCTR_SYM = G_VCTR_FCN(IN1,IN2)
 * Arguments    : const double in1[6]
 *                const double in2[60]
 *                double G_vctr_sym[6]
 * Return Type  : void
 */
void G_vctr_fcn(const double in1[6], const double in2[60], double G_vctr_sym[6])
{
  double t3;
  double t4;
  double t5;
  double t6;
  double t7;
  double t37;
  double t10_tmp;
  double t10;
  double t24;
  double t11;
  double t14_tmp;
  double t14;
  double t16;
  double t17;
  double t20;
  double t22;
  double t25_tmp;
  double t26;
  double t27;
  double t28;
  double t30;
  double t31;
  double t34;
  double t36;
  double t39_tmp;
  double t42;
  double t43;
  double t47;
  double t49;
  double t53;
  double t54;
  double t57_tmp;
  double b_t57_tmp;
  double t57;
  double t60_tmp;
  double b_t60_tmp;
  double t62_tmp;
  double t64;
  double t66;
  double t67;
  double t75;
  double t76;
  double t80;
  double t82_tmp;
  double t82;
  double t85;
  double t87;
  double t89;
  double t90;
  double t93;
  double G_vctr_sym_tmp;
  double b_G_vctr_sym_tmp;
  double c_G_vctr_sym_tmp;

  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     25-Mar-2020 14:58:34 */
  t3 = cos(in1[2]);
  t4 = sin(in1[1]);
  t5 = cos(in1[1]);
  t6 = sin(in1[2]);
  t7 = t4 * 0.181;
  t37 = t3 * t5;
  t10_tmp = t4 * t6;
  t10 = t37 * 9.81 - t10_tmp * 9.81;
  t24 = t5 * t6;
  t11 = t24 * 0.181;
  t14_tmp = t3 * t4;
  t14 = t24 * 9.81 + t14_tmp * 9.81;
  t16 = cos(in1[3]);
  t17 = sin(in1[3]);
  t20 = t14 * t16 + t10 * t17;
  t22 = t6 * (t7 - 0.613);
  t6 = t37 * 0.181;
  t24 = t22 - t6;
  t25_tmp = t11 + t3 * (t7 - 0.613);
  t26 = cos(in1[5]);
  t27 = cos(in1[4]);
  t28 = sin(in1[5]);
  t30 = t10 * t16 - t14 * t17;
  t31 = sin(in1[4]);
  t7 = t17 * t24;
  t34 = t16 * (t25_tmp - 0.571) - t7;
  t36 = t31 * 0.174 + t27 * t34;
  t37 = t16 * t24;
  t39_tmp = t37 + t17 * (t25_tmp - 0.571);
  t42 = t11 + t14_tmp * 0.181;
  t43 = t6 - t10_tmp * 0.181;
  t47 = t16 * t42 + t17 * t43;
  t49 = t16 * t43 - t17 * t42;
  t53 = t27 * 0.174 - t31 * t34;
  t54 = t30 * t31 * t53;
  t24 = t31 * t31;
  t57_tmp = t26 * t27;
  b_t57_tmp = t20 * t28;
  t57 = b_t57_tmp - t57_tmp * t30;
  t60_tmp = t20 * t26;
  b_t60_tmp = t27 * t28;
  t11 = t60_tmp + b_t60_tmp * t30;
  t62_tmp = t20 * t39_tmp;
  t64 = t27 * t27;
  t66 = t37 + t17 * t25_tmp;
  t67 = t27 * t30 * t36;
  t75 = t7 - t16 * t25_tmp;
  t76 = t30 * t34;
  t80 = t28 * t30 + t60_tmp * t27;
  t82_tmp = t20 * t27;
  t82 = t26 * t30 - t82_tmp * t28;
  t85 = t28 * t36 + t26 * (t39_tmp + 0.12);
  t87 = t26 * t36 - t28 * (t39_tmp + 0.12);
  t6 = t20 * t24;
  t89 = t6 * t66;
  t90 = in2[46] * t27 * t30;
  t93 = t6 * t39_tmp;
  G_vctr_sym[0] = 0.0;
  G_vctr_sym_tmp = t20 * t49;
  b_G_vctr_sym_tmp = t30 * t47;
  t17 = G_vctr_sym_tmp * t24;
  t16 = t54 + t57 * t87;
  c_G_vctr_sym_tmp = t11 * t85;
  t14_tmp = ((in2[36] * t30 + in2[38] * t20) + in2[48] * t20) + in2[58] * t11;
  t10_tmp = (t14_tmp + in2[26] * t14) + t90;
  t37 = in2[28] * t10;
  t6 = in2[56] * t57;
  t7 = t62_tmp + t76;
  t24 = in2[47] * t30 * t31;
  t11 = in2[57] * t30 * t31;
  G_vctr_sym[1] = (((((((((t10_tmp - t37) - t6) + in2[29] * (((-t10 * t42 + t14 *
    t43) + t10 * t25_tmp) + t14 * (t22 - t3 * t5 * 0.181))) - in2[59] * ((((t16
    + t80 * (t28 * t47 - t57_tmp * t49)) + t82 * (t26 * t47 + b_t60_tmp * t49))
    - c_G_vctr_sym_tmp) - t17)) + in2[39] * ((t7 + G_vctr_sym_tmp) -
    b_G_vctr_sym_tmp)) + in2[49] * (((((-t54 + t62_tmp) + t67) -
    b_G_vctr_sym_tmp) + t17) + G_vctr_sym_tmp * t64)) + in2[16] * t4 * 9.81) -
                    in2[18] * t5 * 9.81) - t24) - t11;
  G_vctr_sym_tmp = t30 * t75;
  b_G_vctr_sym_tmp = (t54 - t62_tmp) - t67;
  G_vctr_sym[2] = ((((((t10_tmp - in2[59] * ((((t16 + t89) - t80 * (t28 * t75 -
    t57_tmp * t66)) - t82 * (t26 * t75 + b_t60_tmp * t66)) - c_G_vctr_sym_tmp))
                       - t37) - t6) + in2[39] * ((t7 - t20 * t66) +
    G_vctr_sym_tmp)) - in2[49] * (((b_G_vctr_sym_tmp + t89) - G_vctr_sym_tmp) +
    t20 * t64 * t66)) - t24) - t11;
  G_vctr_sym[3] = (((((t14_tmp + t90) - in2[59] * ((((t16 + t93) + t80 * (t28 *
    t34 + t57_tmp * t39_tmp)) + t82 * (t26 * t34 - b_t60_tmp * t39_tmp)) -
    c_G_vctr_sym_tmp)) - t6) - in2[49] * (((b_G_vctr_sym_tmp + t76) + t93) +
    t62_tmp * t64)) - t24) - t11;
  G_vctr_sym[4] = ((((-in2[59] * (((((-t20 * t31 * t36 + t82_tmp * t53) - t26 *
    t53 * t80) + t28 * t53 * t82) + t60_tmp * t31 * t87) + b_t57_tmp * t31 * t85)
                      - in2[46] * t20 * t31) - in2[47] * t20 * t27) - in2[57] *
                    t20 * t27) - in2[56] * t20 * t26 * t31) - in2[58] * t20 *
    t28 * t31;
  G_vctr_sym[5] = in2[56] * t82 + in2[58] * t80;
}

/*
 * File trailer for G_vctr_fcn.c
 *
 * [EOF]
 */
