function M_sym = get_M(in1)
%GET_M
%    M_SYM = GET_M(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    18-Dec-2020 15:33:58

q1 = in1(1,:);
q2 = in1(2,:);
t2 = q1.*2.0;
t3 = q2+t2;
t4 = cos(t3);
t5 = q2.*2.0;
t6 = t2+t5;
t7 = cos(t6);
t8 = t7.*1.596370998963869e-14;
t9 = cos(q2);
t10 = t4.*4.183362156613912e-14;
t11 = t9.*6.200999999874499e-3;
t12 = t8+t10+t11+4.366301599898139e-3;
M_sym = reshape([t4.*8.366724313227824e-14+t8+t9.*1.2401999999749e-2+cos(t2).*1.231610220704716e-13+3.062246659931277e-2,t12,t12,t8+4.366301599898139e-3],[2,2]);
