function g_sym = get_g(in1)
%GET_G
%    G_SYM = GET_G(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    18-Dec-2020 15:33:59

q1 = in1(1,:);
q2 = in1(2,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = t2.*t3.*2.433272399983584e-1;
t5 = sin(q1);
t6 = sin(q2);
g_sym = [t2.*1.095335549992611+t4-t5.*t6.*2.433272399983584e-1;t4-t5.*t6.*2.433272399983584e-1];
