function C_sym = get_C(in1,in2)
%GET_C
%    C_SYM = GET_C(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    18-Dec-2020 15:33:59

q1 = in1(1,:);
q2 = in1(2,:);
qd1 = in2(1,:);
qd2 = in2(2,:);
t2 = q1.*2.0;
t3 = q2+t2;
t4 = sin(t3);
t5 = q2.*2.0;
t6 = t2+t5;
t7 = sin(t6);
t8 = t7.*1.596370998963869e-14;
t9 = t4.*4.183362156613912e-14;
t10 = sin(q2);
t11 = t10.*6.200999999874499e-3;
t12 = t8+t9+t11;
C_sym = reshape([-qd2.*t12-qd1.*(t4.*8.366724313227824e-14+t8+sin(t2).*1.231610220704716e-13),qd2.*t7.*(-1.596370998963869e-14)-qd1.*(t8+t9-t11),-qd1.*t12-qd2.*t12,qd1.*t7.*(-1.596370998963869e-14)-qd2.*t7.*1.596370998963869e-14],[2,2]);
