/*
 * File: M_mtrx_fcn.c
 *
 * MATLAB Coder version            : 4.1
 * C/C++ source code generated on  : 25-Mar-2020 16:38:11
 */

/* Include Files */
#include <math.h>
#include "M_mtrx_fcn.h"

/* Function Definitions */

/*
 * M_MTRX_FCN
 *     M_MTRX_SYM = M_MTRX_FCN(IN1,IN2)
 * Arguments    : const double in1[6]
 *                const double in2[60]
 *                double M_mtrx_sym[36]
 * Return Type  : void
 */
void M_mtrx_fcn(const double in1[6], const double in2[60], double M_mtrx_sym[36])
{
  double t3;
  double t4;
  double t5;
  double t6;
  double t7;
  double t130;
  double t299;
  double t10;
  double t11;
  double t13_tmp;
  double b_t13_tmp;
  double t13;
  double t15;
  double t19_tmp;
  double b_t19_tmp;
  double t19;
  double t20;
  double t21;
  double t24_tmp;
  double b_t24_tmp;
  double t24;
  double t87;
  double t14_tmp_tmp;
  double t14_tmp;
  double t14;
  double t25_tmp;
  double b_t25_tmp;
  double t25;
  double t28;
  double t30;
  double t300;
  double t33_tmp;
  double t34_tmp;
  double t37;
  double t38;
  double t43_tmp;
  double t43;
  double t54_tmp;
  double t45;
  double t46_tmp;
  double t48_tmp;
  double t49_tmp;
  double b_t49_tmp;
  double t49;
  double t57_tmp;
  double b_t57_tmp;
  double t57;
  double t58_tmp;
  double t59_tmp;
  double t62;
  double t63;
  double t67_tmp;
  double t64_tmp;
  double t66;
  double t68;
  double t71_tmp;
  double t71;
  double t72;
  double t89_tmp;
  double t73_tmp;
  double t74;
  double t75;
  double t78;
  double t80;
  double t81_tmp;
  double t81;
  double t86_tmp;
  double t82_tmp;
  double t84_tmp;
  double t85_tmp;
  double t88_tmp;
  double t90_tmp;
  double t92_tmp;
  double t93_tmp;
  double t95_tmp;
  double t95;
  double t96_tmp;
  double t108_tmp;
  double t97_tmp;
  double t100;
  double t101;
  double t121;
  double t104;
  double t107;
  double t109;
  double t112;
  double t114;
  double t117_tmp;
  double t117;
  double t120;
  double t123;
  double t126_tmp;
  double t128;
  double t129;
  double t132;
  double t138;
  double t140;
  double t141;
  double t145;
  double t149_tmp;
  double b_t149_tmp;
  double t149;
  double t150;
  double t151;
  double t152;
  double t155;
  double t156;
  double t157;
  double t158;
  double t159;
  double t160_tmp;
  double t160;
  double t161_tmp;
  double t161;
  double t163_tmp;
  double t167;
  double t172_tmp;
  double t173;
  double t177_tmp;
  double t183_tmp;
  double b_t183_tmp;
  double t200;
  double t205_tmp;
  double t206;
  double t207;
  double t216;
  double t219;
  double t220;
  double t221;
  double t222;
  double t223;
  double t226;
  double t228;
  double t231;
  double t232;
  double t233;
  double t234;
  double t235;
  double t236;
  double t237;
  double t238_tmp;
  double b_t238_tmp;
  double t238;
  double t239_tmp;
  double t240_tmp;
  double t241_tmp;
  double t242_tmp;
  double t243_tmp;
  double t244_tmp;
  double t245_tmp;
  double t248;
  double t249;
  double t253;
  double t254;
  double t256;
  double t258;
  double t259;
  double t261;
  double t266;
  double t269;
  double t271;
  double t273;
  double t277;
  double t278_tmp;
  double t279_tmp;
  double t343_tmp;
  double t292_tmp;
  double t311_tmp;
  double t299_tmp;
  double t300_tmp;
  double t303_tmp;
  double t304_tmp;
  double t307_tmp;
  double b_t307_tmp;
  double c_t307_tmp;
  double d_t307_tmp;
  double e_t307_tmp;
  double t307;
  double t308;
  double t310;
  double t312_tmp;
  double t313_tmp;
  double t314_tmp;
  double t314;
  double t315_tmp;
  double t315;
  double t318_tmp;
  double t320_tmp;
  double t324;
  double t325;
  double t326;
  double t327;
  double t328;
  double t331;
  double t335;
  double t336;
  double t337_tmp;
  double t337;
  double t341;
  double t342;
  double t349;
  double t350_tmp;
  double t365_tmp;
  double b_t365_tmp;
  double c_t365_tmp;
  double d_t365_tmp;
  double e_t365_tmp;
  double t365;
  double t381_tmp;
  double t382_tmp;
  double t383_tmp;
  double t377_tmp;
  double b_t377_tmp;
  double c_t377_tmp;
  double t377;
  double t384;
  double t385;
  double t391;
  double t394;
  double t396;
  double t398;
  double t400;
  double M_mtrx_sym_tmp;
  double b_M_mtrx_sym_tmp;

  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     25-Mar-2020 15:01:27 */
  t3 = cos(in1[1]);
  t4 = sin(in1[2]);
  t5 = cos(in1[2]);
  t6 = sin(in1[1]);
  t7 = cos(in1[3]);
  t130 = t3 * t4;
  t299 = t5 * t6;
  t10 = t130 + t299;
  t11 = sin(in1[3]);
  t13_tmp = t3 * t5;
  b_t13_tmp = t4 * t6;
  t13 = t13_tmp - b_t13_tmp;
  t15 = cos(in1[5]);
  t19_tmp = t7 * t13;
  b_t19_tmp = t10 * t11;
  t19 = t19_tmp - b_t19_tmp;
  t20 = cos(in1[4]);
  t21 = sin(in1[5]);
  t24_tmp = t7 * t10;
  b_t24_tmp = t11 * t13;
  t24 = t24_tmp + b_t24_tmp;
  t87 = t19 * t21;
  t14_tmp_tmp = t15 * t20;
  t14_tmp = t14_tmp_tmp * t24;
  t14 = t87 + t14_tmp;
  t25_tmp = t20 * t21;
  b_t25_tmp = t25_tmp * t24;
  t25 = t15 * t19 - b_t25_tmp;
  t28 = t130 * 0.039 + t299 * 0.039;
  t30 = t13_tmp * 0.039 - b_t13_tmp * 0.039;
  t300 = t7 * t28;
  t33_tmp = t11 * t30;
  t34_tmp = t7 * t30;
  t37 = (t3 * 0.613 + t13_tmp * 0.571) - b_t13_tmp * 0.571;
  t38 = sin(in1[4]);
  t43_tmp = t300 + t33_tmp;
  t43 = (t43_tmp + t24_tmp * 0.135) + b_t24_tmp * 0.135;
  t54_tmp = t11 * t28;
  t45 = ((t34_tmp + t19_tmp * 0.135) - b_t19_tmp * 0.135) - t54_tmp;
  t46_tmp = t20 * t45;
  t48_tmp = t37 * t38;
  t49_tmp = t46_tmp + t48_tmp;
  b_t49_tmp = t24 * t38;
  t49 = t49_tmp - b_t49_tmp * 0.12;
  t57_tmp = t15 * t43;
  b_t57_tmp = t21 * t49;
  t57 = t57_tmp + b_t57_tmp;
  t58_tmp = t15 * t49;
  t59_tmp = t38 * t45;
  t62 = t3 * t3;
  t63 = t6 * t6;
  t67_tmp = t20 * t37;
  t64_tmp = t59_tmp - t67_tmp;
  t66 = t19 * t19;
  t68 = t59_tmp / 2.0;
  t71_tmp = t20 * t24;
  t71 = t71_tmp * 0.12;
  t72 = t64_tmp + t71;
  t89_tmp = t21 * t43;
  t73_tmp = t58_tmp - t89_tmp;
  t74 = t24 * t24;
  t75 = t38 * t38;
  t78 = t87 * 2.0 + t14_tmp * 2.0;
  t49 = t5 * 0.613;
  t80 = t5 * 0.613 + 0.571;
  t81_tmp = t4 * t11;
  t81 = t81_tmp * 0.613;
  t86_tmp = t7 * (t49 + 0.571);
  t82_tmp = t81 - t86_tmp;
  t84_tmp = t4 * t7;
  t85_tmp = t11 * (t49 + 0.571) + t84_tmp * 0.613;
  t87 = t20 * 0.12;
  t88_tmp = t20 * t85_tmp;
  t49 = t87 - t88_tmp;
  t90_tmp = t21 * t82_tmp;
  t92_tmp = t15 * t49;
  t93_tmp = t90_tmp + t92_tmp;
  t45 = t38 * 0.12;
  t95_tmp = t38 * t85_tmp;
  t95 = t45 - t95_tmp;
  t96_tmp = t15 * t82_tmp;
  t108_tmp = t21 * t49;
  t97_tmp = t96_tmp - t108_tmp;
  t100 = t24_tmp * 2.0 + b_t24_tmp * 2.0;
  t101 = t34_tmp - t54_tmp;
  t121 = t67_tmp / 2.0;
  t104 = (t68 + t71_tmp * 0.06) - t121;
  t107 = t57_tmp / 2.0 + b_t57_tmp / 2.0;
  t109 = t58_tmp / 2.0;
  t112 = t130 * 0.0195 + t299 * 0.0195;
  t114 = t13_tmp * 0.0195 - b_t13_tmp * 0.0195;
  t117_tmp = t300 / 2.0 + t33_tmp / 2.0;
  t117 = (t117_tmp + t24_tmp * 0.0675) + b_t24_tmp * 0.0675;
  t120 = t46_tmp / 2.0 + t48_tmp / 2.0;
  t123 = t34_tmp / 2.0 - t54_tmp / 2.0;
  t126_tmp = t81_tmp * 0.3065 - t86_tmp / 2.0;
  t128 = t13_tmp * 2.0 - b_t13_tmp * 2.0;
  t129 = t20 * t20;
  t24_tmp = t15 * t38;
  t130 = t24_tmp * t72;
  t300 = t11 * t38;
  t132 = t45 - t300 * 0.571;
  t33_tmp = t21 * t38;
  t299 = t11 * t20;
  t49 = t87 - t299 * 0.571;
  t45 = t21 * t49;
  t57_tmp = t7 * t15;
  t138 = t45 + t57_tmp * 0.571;
  b_t57_tmp = t15 * t49;
  t58_tmp = t7 * t21;
  t140 = b_t57_tmp - t58_tmp * 0.571;
  t141 = t33_tmp * t73_tmp;
  t49 = t38 * 0.06;
  t145 = t68 - t121;
  t149_tmp = t20 * t49_tmp;
  b_t149_tmp = t38 * t64_tmp;
  t149 = in2[48] * (t149_tmp + b_t149_tmp);
  t150 = in2[31] * t100 / 2.0;
  t151 = in2[38] * t101;
  t152 = t20 * t43;
  t155 = in2[26] * t30;
  t156 = in2[28] * t28;
  b_t24_tmp = in2[51] * t20;
  t157 = b_t24_tmp * t78 / 2.0;
  t87 = in2[41] * t24;
  t158 = t87 * t129;
  t159 = in2[40] * t20 * t24 * t38;
  t160_tmp = in2[50] * t14;
  t160 = t160_tmp * t15 * t38;
  t161_tmp = in2[52] * t21;
  t161 = t161_tmp * t38 * t78 / 2.0;
  t163_tmp = t24_tmp * t57;
  t167 = t14 * t97_tmp;
  t121 = t130 + t20 * t73_tmp;
  t172_tmp = t20 * t57 + t33_tmp * t72;
  t173 = t49 - t95_tmp / 2.0;
  t177_tmp = t96_tmp / 2.0 - t108_tmp / 2.0;
  t183_tmp = t90_tmp / 2.0 + t92_tmp / 2.0;
  b_t183_tmp = t109 - t89_tmp / 2.0;
  t200 = t11 * t80 / 2.0 + t84_tmp * 0.3065;
  t205_tmp = t38 * t43;
  t206 = t71_tmp * t82_tmp;
  t207 = t19 * t20 * t85_tmp;
  t216 = t85_tmp * t85_tmp;
  t219 = t82_tmp * t126_tmp * 2.0;
  t220 = in2[43] * t129;
  t221 = in2[53] * t129;
  t222 = in2[40] * t75;
  t223 = t49 - t300 * 0.2855;
  t226 = t45 / 2.0 + t57_tmp * 0.2855;
  t228 = b_t57_tmp / 2.0 - t58_tmp * 0.2855;
  t231 = t15 * t15;
  t232 = in2[50] * t75 * t231;
  t233 = t21 * t21;
  t234 = in2[55] * t75 * t233;
  t46_tmp = in2[41] * t20 * t38;
  t235 = t46_tmp * 2.0;
  t54_tmp = in2[51] * t15;
  t236 = t54_tmp * t20 * t38 * 2.0;
  t48_tmp = in2[54] * t20;
  t237 = t48_tmp * t21 * t38 * 2.0;
  t238_tmp = in2[52] * t15;
  b_t238_tmp = t238_tmp * t21;
  t238 = b_t238_tmp * t75 * 2.0;
  t239_tmp = t85_tmp * t129;
  t240_tmp = t75 * t85_tmp;
  t241_tmp = t24_tmp * t97_tmp;
  t242_tmp = t33_tmp * t93_tmp;
  t243_tmp = t20 * t93_tmp;
  t244_tmp = t24_tmp * t95;
  t245_tmp = t33_tmp * t95;
  t248 = in2[58] * (((t130 + t20 * t73_tmp) + t14 * t132) - b_t49_tmp * t140);
  t249 = (t172_tmp - t25 * t132) - b_t49_tmp * t138;
  t58_tmp = -t141 + t163_tmp;
  t253 = in2[57] * ((t58_tmp + t14 * t138) + t25 * t140);
  t254 = t107 * t138;
  t256 = t57 * t226;
  t258 = t228 * t73_tmp;
  t259 = t104 * t132;
  t261 = t72 * t223;
  t266 = ((((t299 * t49_tmp * 0.2855 + t299 * t120 * 0.571) + t300 * t64_tmp *
            0.2855) + t300 * t145 * 0.571) - t7 * t43 * 0.2855) - t7 * t117 *
    0.571;
  t49 = t11 * t19;
  t57_tmp = t7 * t20;
  t269 = in2[47] * ((t205_tmp + t57_tmp * t24 * 0.571) - t49 * t20 * 0.571);
  t45 = t7 * t24;
  t271 = (t152 + t49 * t38 * 0.571) - t45 * t38 * 0.571;
  t273 = t49 * 0.571 - t45 * 0.571;
  t277 = in2[39] * (((t7 * t43_tmp * 0.2855 + t7 * t117_tmp * 0.571) - t11 *
                     t101 * 0.2855) - t11 * t123 * 0.571);
  t278_tmp = t20 * t138;
  t279_tmp = t33_tmp * t132;
  t343_tmp = t20 * t97_tmp;
  t292_tmp = t33_tmp * t140;
  t311_tmp = t24_tmp * t138;
  t299_tmp = t11 * t129;
  t299 = t299_tmp * 0.571;
  t300_tmp = t11 * t75;
  t300 = t300_tmp * 0.571;
  t303_tmp = t20 * t140;
  t304_tmp = t24_tmp * t132;
  t49 = t7 * t82_tmp * 0.2855 + t7 * t126_tmp * 0.571;
  t45 = t11 * t85_tmp;
  t307_tmp = t239_tmp + t240_tmp;
  b_t307_tmp = t241_tmp + t242_tmp;
  b_t57_tmp = t243_tmp + t244_tmp;
  c_t307_tmp = in2[26] * t4;
  d_t307_tmp = in2[28] * t5;
  e_t307_tmp = (((((((((in2[23] + in2[33]) + t220) + t221) + t222) + t232) +
                   t234) + t235) + t236) + t237) + t238;
  t307 = ((((((((((((e_t307_tmp + in2[59] * (((((t132 * t173 + t95 * t223) +
    t140 * t183_tmp) + t228 * t93_tmp) - t138 * t177_tmp) - t97_tmp * t226)) +
                    in2[46] * (t20 * t82_tmp - t57_tmp * 0.571)) + d_t307_tmp *
                   0.613) + in2[58] * ((b_t57_tmp + t303_tmp) + t304_tmp)) -
                 c_t307_tmp * 0.613) - in2[36] * ((-t81 + t86_tmp) + t7 * 0.571))
               - in2[38] * (t85_tmp + t11 * 0.571)) - in2[39] * ((t49 - t45 *
    0.2855) - t11 * t200 * 0.571)) - in2[47] * (t38 * t82_tmp - t7 * t38 * 0.571))
            - in2[49] * ((t49 - t300_tmp * t85_tmp * 0.571) - t45 * t129 * 0.571))
           - in2[48] * ((t307_tmp + t299) + t300)) - in2[56] * (((t245_tmp +
             t278_tmp) + t279_tmp) - t343_tmp)) - in2[57] * ((b_t307_tmp +
    t292_tmp) - t311_tmp);
  t308 = t11 * t11;
  t310 = t7 * t7 * 0.326041;
  t312_tmp = t15 * t129;
  t49 = t312_tmp * 0.12;
  t313_tmp = t15 * t75;
  t45 = t313_tmp * 0.12;
  t314_tmp = t21 * t129;
  t314 = t314_tmp * 0.12;
  t315_tmp = t21 * t75;
  t315 = t315_tmp * 0.12;
  t318_tmp = in2[54] * t15;
  t57_tmp = in2[52] * t38;
  t320_tmp = in2[55] * t15;
  t33_tmp = in2[53] * t20;
  t24_tmp = in2[54] * t21;
  t324 = t38 * t72 * 0.06;
  t325 = t38 * t104 * 0.12;
  t326 = t14_tmp_tmp * t73_tmp * 0.06;
  t327 = t25_tmp * t57 * 0.06;
  t328 = t25_tmp * t107 * 0.12;
  t331 = in2[58] * ((t121 + t14 * t38 * 0.12) - t14_tmp * t38 * 0.12);
  t335 = in2[57] * ((t58_tmp + t14_tmp_tmp * t25 * 0.12) + t14 * t20 * t21 *
                    0.12);
  t336 = (t172_tmp - t25 * t38 * 0.12) - b_t25_tmp * t38 * 0.12;
  t337_tmp = in2[47] * t38;
  t337 = t337_tmp * t43;
  t341 = in2[58] * ((b_t57_tmp + t49) + t45);
  t342 = in2[36] * t82_tmp;
  t349 = in2[59] * (((((t38 * t95 * 0.06 + t38 * t173 * 0.12) + t14_tmp_tmp *
                       t93_tmp * 0.06) + t14_tmp_tmp * t183_tmp * 0.12) -
                     t25_tmp * t97_tmp * 0.06) - t25_tmp * t177_tmp * 0.12);
  b_t57_tmp = in2[46] * t20;
  t350_tmp = b_t57_tmp * t82_tmp;
  t365_tmp = ((((((((in2[33] + t220) + t221) + t222) + t232) + t234) + t235) +
               t236) + t237) + t238;
  b_t365_tmp = in2[36] * t7;
  c_t365_tmp = in2[38] * t11;
  d_t365_tmp = in2[46] * t7 * t20;
  e_t365_tmp = in2[47] * t7 * t38;
  t365 = ((((((((t365_tmp + in2[58] * (((t303_tmp + t304_tmp) + t49) + t45)) +
                in2[59] * (((((t38 * t132 * 0.06 + t38 * t223 * 0.12) + t25_tmp *
    t138 * 0.06) + t25_tmp * t226 * 0.12) + t14_tmp_tmp * t140 * 0.06) +
    t14_tmp_tmp * t228 * 0.12)) + e_t365_tmp * 0.571) - in2[48] * (t299 + t300))
             - in2[56] * (((t278_tmp + t279_tmp) + t314) + t315)) - in2[57] *
            (t292_tmp - t311_tmp)) - b_t365_tmp * 0.571) - c_t365_tmp * 0.571) -
    d_t365_tmp * 0.571;
  t45 = in2[51] * t21;
  t381_tmp = b_t24_tmp * t21;
  t382_tmp = t57_tmp * t233;
  t383_tmp = in2[50] * t15 * t21 * t38;
  t377_tmp = in2[56] * t15;
  b_t377_tmp = in2[58] * t21;
  c_t377_tmp = (((in2[44] * t20 + in2[42] * t38) + t318_tmp * t20) + t57_tmp *
                t231) + t320_tmp * t21 * t38;
  t377 = (((((((c_t377_tmp + in2[47] * t20 * t85_tmp) + in2[46] * t38 * t85_tmp)
              - t381_tmp) - t382_tmp) - t383_tmp) - in2[57] * (t15 * t93_tmp -
            t21 * t97_tmp)) - t377_tmp * t95) - b_t377_tmp * t95;
  t384 = in2[47] * t11 * t20 * 0.571;
  t385 = in2[46] * t11 * t38 * 0.571;
  t391 = (((in2[51] * t78 / 2.0 + in2[58] * t73_tmp) - in2[54] * t25) - in2[56] *
          t57) - in2[53] * t24 * t38;
  t49 = (t33_tmp + t54_tmp * t38) + t24_tmp * t38;
  t394 = (t49 + in2[56] * t97_tmp) + in2[58] * t93_tmp;
  t396 = (t49 + in2[58] * t140) - in2[56] * t138;
  t398 = (t49 + in2[58] * t15 * t20 * 0.12) - in2[56] * t20 * t21 * 0.12;
  t400 = t318_tmp - t45;
  M_mtrx_sym_tmp = in2[42] * t19;
  b_M_mtrx_sym_tmp = in2[44] * t19;
  M_mtrx_sym[0] = ((((((((((((((((((((((((((((((((((((((in2[5] + in2[29] * ((t62
    * 0.375769 + t28 * t112 * 2.0) + t30 * t114 * 2.0)) + in2[47] * (t19 *
    t49_tmp * 2.0 + t71_tmp * t43 * 2.0)) + in2[46] * (t19 * t64_tmp * 2.0 +
    b_t49_tmp * t43 * 2.0)) + in2[56] * (t25 * t72 * 2.0 + b_t49_tmp * t57 * 2.0))
    + in2[58] * (t14 * t72 * 2.0 - b_t49_tmp * t73_tmp * 2.0)) + in2[30] * t74)
    + in2[35] * t66) + in2[45] * t66) + in2[20] * (t13 * t13)) + in2[25] * (t10 *
    t10)) + in2[50] * (t14 * t14)) + in2[55] * (t25 * t25)) + in2[48] * (t71_tmp
    * t64_tmp * 2.0 - b_t49_tmp * t49_tmp * 2.0)) + in2[49] * ((t43 * t117 * 2.0
    + t49_tmp * t120 * 2.0) + t64_tmp * (t68 - t20 * t37 / 2.0) * 2.0)) + in2[27]
    * (t10 * t28 * 2.0 + t13 * t30 * 2.0)) + in2[37] * (t24 * t43_tmp * 2.0 +
    t19 * t101 * 2.0)) + in2[57] * (t14 * t57 * 2.0 + t25 * t73_tmp * 2.0)) +
    in2[17] * (t62 * 0.352 + t63 * 0.352)) + in2[19] * (t62 * 0.030976 + t63 *
    0.030976)) + in2[59] * ((t57 * t107 * 2.0 + t104 * ((t59_tmp + t71) -
    t67_tmp) * 2.0) + t73_tmp * (t109 - t21 * t43 / 2.0) * 2.0)) + in2[39] *
    ((t43_tmp * t117_tmp * 2.0 + t123 * (t34_tmp - t11 * t28) * 2.0) + t37 *
     ((t3 * 0.3065 + t13_tmp * 0.2855) - b_t13_tmp * 0.2855) * 2.0)) + in2[10] *
    t62) + in2[15] * t63) + in2[22] * t10 * t128) - in2[36] * t19 * t37 * 2.0) -
    in2[32] * t19 * t100) - in2[38] * t24 * t37 * 2.0) + in2[43] * t74 * t75) +
    in2[40] * t74 * t129) - in2[52] * t25 * t78) + in2[53] * t74 * t75) + in2[12]
    * t3 * t6 * 2.0) - in2[26] * t3 * t10 * 1.226) + in2[28] * t3 * t13 * 1.226)
                      - M_mtrx_sym_tmp * t20 * t24 * 2.0) + b_M_mtrx_sym_tmp *
                     t24 * t38 * 2.0) - t46_tmp * t74 * 2.0) + in2[54] * t24 *
                   t25 * t38 * 2.0) - in2[51] * t24 * t38 * t78;
  t49 = (t149 + t150) + t151;
  t100 = ((((((t49 + t155) + t156) + t157) + t158) + t159) + t160) + t161;
  t59_tmp = in2[24] * t10;
  t62 = in2[21] * t128 / 2.0;
  t63 = in2[34] * t19;
  t67_tmp = in2[36] * t43_tmp;
  M_mtrx_sym_tmp *= t38;
  b_M_mtrx_sym_tmp *= t20;
  t25_tmp = t87 * t75;
  t86_tmp = t48_tmp * t25;
  t14_tmp = in2[43] * t20 * t24 * t38;
  b_t25_tmp = t238_tmp * t25 * t38;
  t81 = t33_tmp * t24 * t38;
  t89_tmp = t54_tmp * t24 * t75;
  t130 = in2[55] * t21 * t25 * t38;
  t90_tmp = t24_tmp * t24 * t75;
  t92_tmp = t25 * t93_tmp;
  t108_tmp = (((((t100 + in2[58] * ((t121 + t14 * t95) - b_t49_tmp * t93_tmp)) +
                 in2[59] * (((((t72 * t173 + t95 * t104) + t183_tmp * t73_tmp) +
    t93_tmp * b_t183_tmp) - t97_tmp * t107) - t57 * t177_tmp)) + in2[29] * (((t5
    * t28 * 0.3065 + t5 * t112 * 0.613) - t4 * t30 * 0.3065) - t4 * t114 * 0.613))
               + in2[27] * (t5 * t10 * 0.613 - t4 * t13 * 0.613)) + in2[16] * t3
              * 0.176) + in2[18] * t6 * 0.176;
  t96_tmp = in2[37] * (t24 * t82_tmp + t19 * t85_tmp);
  t121 = in2[39] * (((t85_tmp * t123 + t101 * t200) + t82_tmp * t117_tmp) +
                    t43_tmp * t126_tmp);
  t87 = in2[46] * ((t152 + t19 * t38 * t85_tmp) + b_t49_tmp * t82_tmp);
  t54_tmp = in2[49] * (((((t149_tmp * t85_tmp / 2.0 + t88_tmp * t120) +
    b_t149_tmp * t85_tmp / 2.0) + t95_tmp * t145) + t82_tmp * t117) + t43 *
                       t126_tmp);
  t48_tmp = in2[56] * ((t172_tmp + b_t49_tmp * t97_tmp) - t25 * t95);
  t46_tmp = in2[11] * t3;
  b_t24_tmp = in2[14] * t6;
  M_mtrx_sym[1] = ((((((((((((((((((((((t108_tmp - in2[57] * (((t141 - t163_tmp)
    + t167) - t92_tmp)) - t59_tmp) - t62) - t63) - t67_tmp) - t96_tmp) - t121) -
    t87) - t54_tmp) - t48_tmp) - in2[47] * ((-t205_tmp + t206) + t207)) -
    t46_tmp) - b_t24_tmp) - M_mtrx_sym_tmp) - b_M_mtrx_sym_tmp) - t25_tmp) -
                        t86_tmp) - t14_tmp) - b_t25_tmp) - t81) - t89_tmp) -
                   t130) - t90_tmp;
  M_mtrx_sym[2] = ((((((((((((((((((((((t100 + t248) + t253) + t269) + t277) -
    t59_tmp) - t62) - t63) - t67_tmp) - in2[37] * t273) - in2[46] * t271) - in2
    [49] * t266) - in2[56] * t249) + in2[59] * (((((t254 + t256) + t258) + t259)
    + t261) + t140 * b_t183_tmp)) - M_mtrx_sym_tmp) - b_M_mtrx_sym_tmp) -
    t25_tmp) - t86_tmp) - t14_tmp) - b_t25_tmp) - t81) - t89_tmp) - t130) -
    t90_tmp;
  M_mtrx_sym[3] = ((((((((((((((((((((((t49 + t157) + t158) + t159) + t160) +
    t161) + t331) + t335) + t337) - t63) - t67_tmp) - in2[56] * t336) + in2[59] *
    (((((t324 + t325) + t326) + t327) + t328) + t14_tmp_tmp * b_t183_tmp * 0.12))
    - M_mtrx_sym_tmp) - b_M_mtrx_sym_tmp) - t25_tmp) - b_t57_tmp * t43) -
                        t86_tmp) - t14_tmp) - b_t25_tmp) - t81) - t89_tmp) -
                   t130) - t90_tmp;
  t100 = ((in2[42] * t20 * t24 + t238_tmp * t78 / 2.0) + t161_tmp * t25) + t45 *
    t24 * t38;
  t24_tmp = in2[46] * t64_tmp;
  t33_tmp = in2[47] * t49_tmp;
  t299 = in2[57] * (t15 * t73_tmp + t21 * t57);
  t300 = in2[44] * t24 * t38;
  t58_tmp = t160_tmp * t21;
  t57_tmp = t320_tmp * t25;
  b_t57_tmp = t377_tmp * t72;
  t45 = b_t377_tmp * t72;
  t49 = t318_tmp * t24 * t38;
  M_mtrx_sym[4] = (((((((((t100 - t24_tmp) - t33_tmp) - t299) - in2[45] *
                        (t19_tmp * 2.0 - b_t19_tmp * 2.0) / 2.0) - t300) -
                      t58_tmp) - t57_tmp) - b_t57_tmp) - t45) - t49;
  M_mtrx_sym[5] = t391;
  M_mtrx_sym[6] = ((((((((((((((((((((((t108_tmp - in2[57] * (((t141 + t167) -
    t92_tmp) - t163_tmp)) - t59_tmp) - t62) - t63) - t67_tmp) - t96_tmp) - t121)
    - t87) - t54_tmp) - t48_tmp) - in2[47] * ((t206 + t207) - t205_tmp)) -
    t46_tmp) - b_t24_tmp) - M_mtrx_sym_tmp) - b_M_mtrx_sym_tmp) - t25_tmp) -
                        t86_tmp) - t14_tmp) - b_t25_tmp) - t81) - t89_tmp) -
                   t130) - t90_tmp;
  M_mtrx_sym_tmp = t337_tmp * t82_tmp;
  M_mtrx_sym[7] = ((((((((((((((((((((((((in2[13] + in2[23]) + in2[33]) + t220)
    + t221) + t222) + t232) + t234) + t235) + t236) + t237) + t238) + in2[59] *
    ((t95 * t173 * 2.0 + t97_tmp * t177_tmp * 2.0) + t93_tmp * t183_tmp * 2.0))
    + in2[56] * (t343_tmp * 2.0 - t245_tmp * 2.0)) + in2[58] * (t243_tmp * 2.0 +
    t244_tmp * 2.0)) + in2[49] * ((t219 + t75 * t216) + t129 * t216)) -
    c_t307_tmp * 1.226) + d_t307_tmp * 1.226) + in2[29] * (t4 * t4 * 0.375769 +
    t5 * t5 * 0.375769)) - in2[57] * (t241_tmp * 2.0 + t242_tmp * 2.0)) + in2[36]
                       * (t81_tmp * 1.226 - t7 * t80 * 2.0)) - in2[38] *
                      (t84_tmp * 1.226 + t11 * t80 * 2.0)) - in2[48] * (t240_tmp
    * 2.0 + t239_tmp * 2.0)) + in2[39] * (t219 + t85_tmp * t200 * 2.0)) -
                   M_mtrx_sym_tmp * 2.0) + t350_tmp * 2.0;
  M_mtrx_sym[8] = t307;
  M_mtrx_sym[9] = ((((((((t365_tmp + t341) + t342) + t349) + t350_tmp) - in2[38]
                      * t85_tmp) - in2[48] * t307_tmp) - in2[57] * b_t307_tmp) -
                   in2[56] * (((t245_tmp + t314) + t315) - t343_tmp)) -
    M_mtrx_sym_tmp;
  M_mtrx_sym[10] = t377;
  M_mtrx_sym[11] = t394;
  M_mtrx_sym[12] = (((((((((((((((((((((((((((((((t149 + t150) + t151) + t155) +
    t156) + t157) + t158) + t159) + t160) + t161) + t248) + t253) + t269) + t277)
    - in2[24] * t10) - in2[21] * t128 / 2.0) - in2[34] * t19) - in2[36] *
    t43_tmp) - in2[37] * t273) - in2[46] * t271) - in2[49] * t266) - in2[56] *
    t249) + in2[59] * (((((t254 + t256) + t258) + t259) + t261) + t140 * (t109 -
    t21 * t43 / 2.0))) - in2[42] * t19 * t38) - in2[44] * t19 * t20) - in2[41] *
    t24 * t75) - in2[54] * t20 * t25) - in2[43] * t20 * t24 * t38) - in2[52] *
                       t15 * t25 * t38) - in2[53] * t20 * t24 * t38) - in2[51] *
                     t15 * t24 * t75) - in2[55] * t21 * t25 * t38) - in2[54] *
    t21 * t24 * t75;
  M_mtrx_sym[13] = t307;
  M_mtrx_sym[14] = ((((((((((e_t307_tmp + in2[59] * ((t132 * t223 * 2.0 + t138 *
    t226 * 2.0) + t140 * t228 * 2.0)) + in2[49] * ((t310 + t75 * t308 * 0.326041)
    + t129 * t308 * 0.326041)) - in2[56] * (t278_tmp * 2.0 + t279_tmp * 2.0)) +
    in2[58] * (t303_tmp * 2.0 + t304_tmp * 2.0)) + in2[57] * (t311_tmp * 2.0 -
    t292_tmp * 2.0)) - in2[48] * (t300_tmp * 1.142 + t299_tmp * 1.142)) + in2[39]
                       * (t310 + t308 * 0.326041)) - b_t365_tmp * 1.142) -
                     c_t365_tmp * 1.142) - d_t365_tmp * 1.142) + e_t365_tmp *
    1.142;
  M_mtrx_sym[15] = t365;
  M_mtrx_sym_tmp = ((c_t377_tmp - t381_tmp) - t382_tmp) - t383_tmp;
  b_M_mtrx_sym_tmp = in2[57] * (t15 * t140 + t21 * t138);
  t59_tmp = t377_tmp * t132;
  t62 = b_t377_tmp * t132;
  M_mtrx_sym[16] = ((((M_mtrx_sym_tmp + t384) + t385) - b_M_mtrx_sym_tmp) -
                    t59_tmp) - t62;
  M_mtrx_sym[17] = t396;
  M_mtrx_sym[18] = ((((((((((((((((((((((((t149 + t150) + t151) + t157) + t158)
    + t159) + t160) + t161) + t331) + t335) + t337) - in2[34] * t19) - in2[36] *
    t43_tmp) - in2[56] * t336) + in2[59] * (((((t324 + t325) + t326) + t327) +
    t328) + t15 * t20 * (t109 - t21 * t43 / 2.0) * 0.12)) - in2[42] * t19 * t38)
    - in2[44] * t19 * t20) - in2[41] * t24 * t75) - in2[46] * t20 * t43) - in2
    [54] * t20 * t25) - in2[43] * t20 * t24 * t38) - in2[52] * t15 * t25 * t38)
                      - in2[53] * t20 * t24 * t38) - in2[51] * t15 * t24 * t75)
                    - in2[55] * t21 * t25 * t38) - in2[54] * t21 * t24 * t75;
  M_mtrx_sym[19] = (((((((((((((((((in2[33] + t220) + t221) + t222) + t232) +
    t234) + t235) + t236) + t237) + t238) + t341) + t342) + t349) + t350_tmp) -
                       in2[38] * t85_tmp) - in2[48] * t307_tmp) - in2[57] *
                     b_t307_tmp) - in2[56] * (((t245_tmp + t314) + t315) - t20 *
    t97_tmp)) - in2[47] * t38 * t82_tmp;
  M_mtrx_sym[20] = t365;
  M_mtrx_sym[21] = ((t365_tmp + in2[59] * ((t75 * 0.0144 + t129 * t231 * 0.0144)
    + t129 * t233 * 0.0144)) - in2[56] * (t315_tmp * 0.24 + t314_tmp * 0.24)) +
    in2[58] * (t313_tmp * 0.24 + t312_tmp * 0.24);
  t63 = in2[57] * (t20 * t231 * 0.12 + t20 * t233 * 0.12);
  t67_tmp = t377_tmp * t38 * 0.12;
  t25_tmp = b_t377_tmp * t38 * 0.12;
  M_mtrx_sym[22] = ((M_mtrx_sym_tmp - t63) - t67_tmp) - t25_tmp;
  M_mtrx_sym[23] = t398;
  M_mtrx_sym[24] = (((((((((t100 - in2[45] * t19) - t24_tmp) - t33_tmp) - t299)
                        - t300) - t58_tmp) - t57_tmp) - b_t57_tmp) - t45) - t49;
  M_mtrx_sym[25] = t377;
  M_mtrx_sym[26] = (((((((c_t377_tmp + t384) + t385) - b_M_mtrx_sym_tmp) -
                       t381_tmp) - t59_tmp) - t62) - t382_tmp) - t383_tmp;
  M_mtrx_sym[27] = (((((c_t377_tmp - t63) - t381_tmp) - t67_tmp) - t25_tmp) -
                    t382_tmp) - t383_tmp;
  M_mtrx_sym[28] = ((in2[45] + in2[50] * t233) + in2[55] * t231) - b_t238_tmp *
    2.0;
  M_mtrx_sym[29] = t400;
  M_mtrx_sym[30] = t391;
  M_mtrx_sym[31] = t394;
  M_mtrx_sym[32] = t396;
  M_mtrx_sym[33] = t398;
  M_mtrx_sym[34] = t400;
  M_mtrx_sym[35] = in2[53];
}

/*
 * File trailer for M_mtrx_fcn.c
 *
 * [EOF]
 */
